### PR TITLE
Finished my footer (I'm happy)

### PR DESCRIPTION
**Pull request by Pedro-Pan**
I'm so tired plz `review` and tell me what :heart:

### CODE REVIEW

**Review by gkosmo — APPROVED** [review]
Thank you for this Pedro, it looks good. 

I have a question, should it be rendered somewhere maybe :thinking:  ?

**Comment by Pedro-Pan** [comment]
Ill take a loook, thanks :heart_eyes:

**Comment by Pedro-Pan** [comment]
Hey heres the modifications you requested, and check this out:
image

**Comment by gkosmo** [comment]
This makes a little bit more sense -- keep up the good work !

**Pull request merged**
